// apps/remote-svelte/src/App.svelte
<script>
  import Router from "svelte-spa-router";
  import Home from "./pages/Home.svelte";
  import About from "./pages/About.svelte";

  let { user } = $props();

  const routes = {
    "/": Home,
    "/about": About,
  };
</script>

<div>
  <nav>
    <a href="#/">Home</a> |
    <a href="#/about">About</a>
    {#if user}
      <span style="float: right">{user.name} ({user.email})</span>
    {/if}
  </nav>
  <Router {routes} />
</div>

// apps/remote-one/src/App.tsx
import { Routes, Route, Link, Outlet } from "react-router-dom";
import type { PlatformUser } from "@mfe-poc/platform-types";
import Dashboard from "./pages/Dashboard";
import Settings from "./pages/Settings";

interface AppProps {
  user?: PlatformUser;
}

function Layout({ user }: { user?: PlatformUser }) {
  return (
    <div>
      <nav>
        <Link to=".">Dashboard</Link> | <Link to="settings">Settings</Link>
        {user && <span style={{ float: "right" }}>{user.name} ({user.email})</span>}
      </nav>
      <Outlet />
    </div>
  );
}

export default function App({ user }: AppProps) {
  return (
    <div>
      <Routes>
        <Route path="/" element={<Layout user={user} />}>
          <Route index element={<Dashboard />} />
          <Route path="settings" element={<Settings />} />
        </Route>
      </Routes>
    </div>
  );
}
