// apps/remote-vue/src/App.vue
<script setup lang="ts">
defineProps<{
  user?: { name: string; email: string };
}>();
</script>

<template>
  <div>
    <nav>
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link>
      <span v-if="user" style="float: right">{{ user.name }} ({{ user.email }})</span>
    </nav>
    <router-view />
  </div>
</template>

// apps/remote-svelte/src/App.svelte
<script>
  import Router from "svelte-spa-router";
  import Home from "./pages/Home.svelte";
  import About from "./pages/About.svelte";

  let { user } = $props();

  const routes = {
    "/": Home,
    "/about": About,
  };
</script>

<div>
  <nav>
    <a href="#/">Home</a> |
    <a href="#/about">About</a>
    {#if user}
      <span style="float: right">{user.name} ({user.email})</span>
    {/if}
  </nav>
  <Router {routes} />
</div>
